# src/exporter.py
"""
Exporter Module for saving Spark DataFrames to single CSV files.

Why this file exists:
By default, Apache Spark is a distributed processing engine. When you run 
`df.write.csv("path")`, Spark writes data in parallel from multiple executor nodes. 
This results in a DIRECTORY named "path" containing multiple partition files 
(e.g., `part-00000-xyz.csv`, `part-00001-xyz.csv`).
For a desktop/web application dashboard, the user expects a single, standard CSV file. 
This module solves that problem by coalescing the DataFrame into a single partition, 
writing it to a temporary directory, extracting the generated CSV file, renaming it, 
and cleaning up Spark's metadata files.

Viva Tips:
- Why does Spark write folders instead of files? Because Spark is designed for big data. 
  Writing a single file from thousands of cluster nodes would create a write bottleneck. 
  Writing separate partition files allows parallel write operations.
- What does `.coalesce(1)` do? It reduces the number of partitions in a DataFrame to 1 
  without triggering a full shuffle of data across the network, making it highly efficient.
- What is `shutil` used for? Python's standard library for high-level file and folder operations 
  (like recursively deleting folders or copying files).
"""

import os
import shutil
from pyspark.sql import DataFrame

def export_to_csv(df: DataFrame, target_file_path: str):
    """
    Saves a Spark DataFrame as a single CSV file at the specified path.
    
    Parameters:
    df (DataFrame): The Spark DataFrame to export.
    target_file_path (str): The final destination path for the CSV (e.g., 'output/top_10.csv').
    """
    # Create the parent directories for the target file if they don't exist
    target_dir = os.path.dirname(target_file_path)
    if target_dir and not os.path.exists(target_dir):
        os.makedirs(target_dir)

    # Use a temporary directory to let Spark write its partition files
    temp_dir = target_file_path + "_temp"
    
    try:
        # 1. Coalesce the DataFrame to 1 partition.
        # 2. Write as CSV with header.
        # 3. Overwrite if directory exists.
        df.coalesce(1).write \
            .mode("overwrite") \
            .option("header", "true") \
            .csv(temp_dir)
            
        # Find the actual part-xxxxx.csv file inside the temp folder
        part_file = None
        for filename in os.listdir(temp_dir):
            if filename.startswith("part-") and filename.endswith(".csv"):
                part_file = os.path.join(temp_dir, filename)
                break
                
        if part_file:
            # Overwrite the target file if it already exists
            if os.path.exists(target_file_path):
                os.remove(target_file_path)
            # Copy and rename the part-file to the target destination
            shutil.copy(part_file, target_file_path)
        else:
            raise IOError("Spark did not generate any partition CSV file.")
            
    finally:
        # Clean up the temporary folder generated by Spark
        if os.path.exists(temp_dir):
            shutil.rmtree(temp_dir)
            
    print(f"Successfully exported report to: {target_file_path}")
